# -*- coding: utf-8 -*-
"""llegoaltren.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kg9gKXaqJPiXbFabjNCevDxRqnNE0Kv1
"""

def hora_minutos (hora,min):
  hora_total = (hora * 60) + min
  return hora_total
#conversion de horas a minutos

def calcular_diferencia(hora_actual, min_actual, hora_tren, min_tren):
    minutos_actuales = hora_minutos (hora_actual, min_actual)
    minutos_tren = hora_minutos (hora_tren, min_tren)
    diferencia = minutos_tren - minutos_actuales
#diferencia de minutos entre la hora actual y la llegada del tren

def tren():
  print("¿LLEGO A TOMARME EL TREN?")
  print("")
  print("¿Qué hora es?")

  hora_actual = int(input("Hora actual (0-23) "))
  min_actual = int(input("Minutos (0-59) "))

  print("¿A que hora llega el tren que queres tomarte?")

  hora_tren = int(input("Hora tren (0-23) "))
  min_tren = int(input("Minutos (0-59) "))

  #ACA HAY ERROR pues da none"
  diferencia_min = calcular_diferencia(hora_actual, min_actual, hora_tren, min_tren)

  print(diferencia_min)
  print("¿En qué pabellon estas?")
  print("¿1, 2, 3, 0?")
  print("nota: 1 es fadu , 2 es naturales, 3 es matematicas, 0 es computacion")

  pabellon = int(input())

  if pabellon == 1:
    if diferencia_min > 0:
      print("llegas!")
    else: print("no llegas")

tren()